//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

use sea_orm::entity::prelude::*;
use serde::Deserialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub uuid: String,
    pub first_ip: String,
    pub last_ip: String,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::survival_economy::Entity")]
    SurvivalEconomy,
}

impl Related<super::survival_economy::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SurvivalEconomy.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
